import DEFAULT_CANVAS_SIZE from './DEFAULT_CANVAS_SIZE';
import DEFAULT_OFFSET from './DEFAULT_OFFSET';
import DEFAULT_SCALE from './DEFAULT_SCALE';
import PREFIX_CLASS from './PREFIX_CLASS';
import ZOOM_RANGE from './ZOOM_RANGE';

export { DEFAULT_CANVAS_SIZE, ZOOM_RANGE, DEFAULT_OFFSET, DEFAULT_SCALE, PREFIX_CLASS };
